### ISSUE TITLE
[BUG]iOS的演示示例, 图片设置1920x1080 ，人脸检测正常，视频设置1920x1080 ，人脸检测失效。

### ISSUE THREAD

**Issue by lusaProject** [pixpark/gpupixel#104]
iOS的演示示例, 图片设置1920x1080 ，人脸检测正常，视频设置1920x1080 ，人脸检测失效，是什么原因？

**Comment by jaaronkot** [comment]
已  fix, 这个地方修改 width 传错了，改为 stride, 参考 https://github.com/pixpark/gpupixel/commit/cab8aa4ababf327e4082d8cb343f980a59e0d824

**Comment by lusaProject** [comment]
感谢帮助
