### ISSUE TITLE
[BUG]瘦脸后只要手臂一挥一遮挡脸部，人脸识别就失效

### ISSUE THREAD

**Issue by ffasdz** [pixpark/gpupixel#107]
1.瘦脸后只要手臂一挥一遮挡脸部，人脸识别就失效，瘦脸就没起效果
2.人脸识别暂时只有1280X720有用
3.脸离屏幕边缘近一点就会有一部分花屏

**Comment by jaaronkot** [comment]
ios  1080p 分辨率， demo中图像宽度传递错误，已fix， 参考https://github.com/pixpark/gpupixel/commit/cab8aa4ababf327e4082d8cb343f980a59e0d824

**Comment by jaaronkot** [comment]
人脸遮挡识别失败，因为使用的是三方人脸识别库，这个也无法控制，暂时无解

**Comment by ffasdz** [comment]
> 人脸识别失败，因为使用的是三方人脸识别库，这个也无法控制，暂时无解
使用mediapipe识别控制平滑和允许丢帧数，会不会好一点？

**Comment by ffasdz** [comment]
> 人脸遮挡识别失败，因为使用的是三方人脸识别库，这个也无法控制，暂时无解

用mediapipe来识别，使用平滑和允许丢帧数实现不知道改动后如何？但只是测试识别脸部的话，效果好像会更好一点
