### ISSUE TITLE
When will face++be replaced with vnn? 

### ISSUE THREAD

**Issue by xfbedev** [pixpark/gpupixel#11]
Face++ has limitations and many features require the use of landmarks.

**Comment by gezhaoyou** [comment]
I don’t have much time, maybe two to three months.

**Comment by WoYang** [comment]
是不是可以考虑使用MediaPie替换Face++实现人脸轮廓检测

**Comment by gezhaoyou** [comment]
> 是不是可以考虑使用MediaPie替换Face++实现人脸轮廓检测

感谢，最近也注意到了这个库，现在正在选型，还没最终决定用哪个库做

**Comment by gezhaoyou** [comment]
测试了下iOS平台，MediaPipe CPU：50% ~ 65%，Face++: 35% ~ 45% ，8核总计CPU（800%），也还好，可以考虑MediaPiPe，毕竟也跨平台

**Comment by gezhaoyou** [comment]
The face landmark detection has replace [Face++](https://www.faceplusplus.com.cn/) with [VNN](https://github.com/joyycom/VNN) from [v1.2.0](https://github.com/pixpark/gpupixel/releases/tag/v1.2.0), no more verification requirements are needed.
