### ISSUE TITLE
Android : App crashed on start 

### ISSUE THREAD

**Issue by Menghang01** [pixpark/gpupixel#15]
I tried to run on android device ( Pixel 2 ). After granting camera access, the application crashed, displaying the following errors.

<img width="1282" alt="Screenshot 2024-02-01 at 4 57 18 in the afternoon" src="https://github.com/pixpark/gpupixel/assets/55906679/0785a180-88db-4443-813e-93cb3ad3f776">

**Comment by rn-netizen** [comment]
What is the fix?
