### ISSUE TITLE
Clion Windows build segfall

### ISSUE THREAD

**Issue by HenryScratch** [pixpark/gpupixel#17]
building `examples/desktop` via CLion on Windows

I can successfully build application(after building the library)

When running with demo image everything is ok, but when I try to load another image instead of your `demo.jpg` file, I get Segfault at the line `gpuSourceImage = SourceImage::create("other_img.jpg")`.

After some reseach it was found out that segfault occurs in the `SourceImage::init` function when trying to call `glTexImage2D` in line 60 when loading image into opengl.

https://github.com/pixpark/gpupixel/blob/7d0d3ee43057a16c5a9b874ad111d3a643ec2360/src/source/source_image.cc#L60

can you tell me what to do to fix this error? not much experience with opengl

thanks

**Comment by gezhaoyou** [comment]
Need more info, or give your test image
