### ISSUE TITLE
嘴唇和腮红的TextureBounds是怎么得来的

### ISSUE THREAD

**Issue by dsxlong** [pixpark/gpupixel#19]
你好，我看到示例中有口红和腮红的贴图，但是bounds是写死的，这个依据是什么？
![image](https://github.com/pixpark/gpupixel/assets/13047073/234b0fca-bbf6-48b8-8975-bb1fc5bf6b39)

**Comment by gezhaoyou** [comment]
see: https://github.com/pixpark/gpupixel/issues/9
