### ISSUE TITLE
为什么在ios上....demo工程可以运行,我把demo工程中的framework取出来放到空工程中,引用头文件就报 'memory' file not found  c++文件无法查询,但是我不引用头文件，自己引用memory就不会报错

### ISSUE THREAD

**Issue by ShinyHeng** [pixpark/gpupixel#2]

**Comment by gezhaoyou** [comment]
检查下工程配置：

**Comment by gezhaoyou** [comment]
尝试下1.0.5版本，在此版本之前demo工程中需要定义 GPUPIXEL_IOS宏，1.0.5版本不需要demo有额外设置

**Comment by leehiuleong** [comment]
v1.3.0 beta4 ios端 ，framework加入空项目里 ，编译还是会有'memory' file not found的问题

**Comment by leehiuleong** [comment]
> v1.3.0 beta4 ios端 ，framework加入空项目里 ，编译还是会有'memory' file not found的问题

调用文件.m 改.mm解决了
