### ISSUE TITLE
有计划支持CameraX吗？

### ISSUE THREAD

**Issue by WoYang** [pixpark/gpupixel#20]

**Comment by WoYang** [comment]
![Camera](https://github.com/pixpark/gpupixel/assets/5896347/4f74e1af-b0fc-414c-a548-b4a22afb9e03)

根据Android版本源码，我初步画了一个时序图，并且按照这个时序图重构成CameraX，发现把ImageAnalysis预览数据通过 ImageView可以展示出来，但是Camera就是黑屏

**Comment by gezhaoyou** [comment]
感谢反馈，最近会看下CameraX相关的资料，理论上支持起来不难

**Comment by WoYang** [comment]
> 感谢反馈，最近会看下CameraX相关的资料，理论上支持起来不难

我再重新整理下代码、看是不是遗漏了某个细节

**Comment by jarronkot** [comment]
gpupixel 主要提供图像处理的核心能力，相机采集不是其重点，遂关闭
