### ISSUE TITLE
使用自带例子，gpupixel_app段错误

### ISSUE THREAD

**Issue by faxiangui** [pixpark/gpupixel#28]
wsl2 下ubuntu20.04
![无标题](https://github.com/pixpark/gpupixel/assets/14360723/9baa7965-59a4-45ef-8463-6509b663213e)

**Comment by gezhaoyou** [comment]
wsl2 没试过, 可以用vscode安装cmake插件调试下或者加下日志调下

**Comment by gezhaoyou** [comment]
如果能解决希望提个 PR
