### ISSUE TITLE
瘦脸算法是否支持实时视频

### ISSUE THREAD

**Issue by qian-jiang** [pixpark/gpupixel#29]
想请教一下作者，瘦脸算法是否可以支持实时视频使用，我尝试使用液波或本地平移算法对视频都没有很好的效果，作者有使用过类似的实时瘦脸算法吗，非常感谢

**Comment by gezhaoyou** [comment]
支持,可以从摄像头读取yuv或者rgb的数据, 也可以读取视频文件,解码成yuv 送入gpupixel

**Comment by qian-jiang** [comment]
> 支持，可以从摄像头读取yuv或者rgb的数据，也可以读取视频文件，解码成yuv送入gpupixel

大佬，这个瘦脸算法方便讲下使用的哪个算法吗，我尝试使用仿射变换去实现，对单张图片效果可以，应用到视频上人脸连续性较差，今天尝试编译windows版本，c++14环境编译不了，想请教下使用什么算法对实时瘦脸有效，感谢
