### ISSUE TITLE
[Linux] Linux demo can't work on main branch

### ISSUE THREAD

**Issue by AlvinChen1028** [pixpark/gpupixel#30]
2 issues:
1. Linux demo can't be linked as VNN lib directory is not added in link path. To fix it, please refer attached picture.
2. The demo can run, but the FB doesn't take effect, the output image is not beatified. Please refer the attached picture.
![MicrosoftTeams-image (5)](https://github.com/pixpark/gpupixel/assets/58837495/d9501e46-ba36-43b9-95a8-11c4042d9689)
![MicrosoftTeams-image (4)](https://github.com/pixpark/gpupixel/assets/58837495/4197f9e1-69b8-41d8-82cf-cdf5d8ee3029)

**Comment by kelinkong** [comment]
I also encountered these two problems. Thank you for solving the first problem!

**Comment by gezhaoyou** [comment]
> I also encountered these two problems. Thank you for solving the first problem!

Every commit push will triger Github Action 
 Build : @See https://github.com/pixpark/gpupixel/actions/runs/8505339967/job/23293657348

**Comment by kelinkong** [comment]
> > I also encountered these two problems. Thank you for solving the first problem!
> 
> Every commit push will triger Github Action Build : @see https://github.com/pixpark/gpupixel/actions/runs/8505339967/job/23293657348, Linux build well. There may be differences in the compilation environment.

Thank you for your reply. Yes, I saw that the GitHub Action was successfully executed, and it was indeed caused by a different compilation environment.
