### ISSUE TITLE
如何使用vs进行编译？

### ISSUE THREAD

**Issue by qian-jiang** [pixpark/gpupixel#31]
使用cmake编译总是报错语法错误，请教下如何使用vs导入项目进行编译，多谢

**Comment by gezhaoyou** [comment]
你好，可以贴出错误看一下，cmake 也是可以生成 vs工程的

**Comment by qian-jiang** [comment]
> 你好，可以贴出错误看看一下，cmake也可以生成vs工程的

目前卡在vnn_core.dll，我不太懂这个，无法解决。
![image](https://github.com/pixpark/gpupixel/assets/26248167/3f985cab-95fb-4c64-913d-d5b6d760d334)

**Comment by gezhaoyou** [comment]
建议搜索下相关错误关键字，大概率是库链接设置错误，或者x86，x64架构是否匹配问题：
参考：https://blog.csdn.net/qq_43331089/article/details/128802279
