### ISSUE TITLE
在android studio上跑不起来，求指点

### ISSUE THREAD

**Issue by 745ujx** [pixpark/gpupixel#36]
![3](https://github.com/pixpark/gpupixel/assets/101161967/c0794bd1-bb3e-4a26-acd9-e03733387e25)

**Comment by LiamKeh** [comment]
可能的原因：

**Comment by LiamKeh** [comment]
可能的原因:
1. 架构不对，gpupixel 默认只编译了arm64-v8a版本；
2. so库放置的位置不对；

建议：
建议直接使用 gpupixel里的.aar库，包含了库用到的依赖资源文件
https://github.com/pixpark/gpupixel/releases/download/v1.2.4/gpupixel_android_arm64_v8a.zip

**Comment by 18818474455** [comment]
> 可能的原因：
> 
> 1. 架构不对，gpupixel默认只编译了arm64-v8a版本；
> 2. 库房放置的位置正确；
> 
> 建议： 直接使用gpupixel里的.aar库，包含了库消耗建议的依赖资源文件 https://github.com/pixpark/gpupixel/releases/download/v1.2.4/gpupixel_android_arm64_v8a.zip

有开发想找你合作，微信多少呢？

**Comment by cijiugechu** [comment]
> ![3](https://private-user-images.githubusercontent.com/101161967/311494221-c0794bd1-bb3e-4a26-acd9-e03733387e25.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNDgxNjAsIm5iZiI6MTcxMzE0Nzg2MCwicGF0aCI6Ii8xMDExNjE5NjcvMzExNDk0MjIxLWMwNzk0YmQxLWJiM2UtNGEyNi1hY2Q5LWUwMzczMzM4N2UyNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwMjI0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Y2QzZGFmNGE5MTkxNmIxYmUyNjMzMjI0YjdjZTY4NjdjNDhiYmI1YWQ3MWZjMjA4ODZmNjQ2YjUwOWM0OWJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CSACYdPLiMHE6xz0L1tBCbbP9_UWD42Sbkyq6DECMqM)

建议在 abiFilter 里和 split->abi 里添加 armeabi-v7a ，然后直接在真机上调试，模拟器的架构是 x86_64, vnn 只支持 armeabi-v7a

**Comment by woshitxm** [comment]
缺少.so文件是环境配置问题。架构不对表现为app运行闪退
