### ISSUE TITLE
[BUG]Windows上运行时，软件窗体最大化时，输出的数据会有脏数据（脏数据是整个软件窗口的画面，相机画面没有充满整个窗体，只处理相机画面）

### ISSUE THREAD

**Issue by KakaWan** [pixpark/gpupixel#61]
有人遇到同样的问题么？有什么解决办法？

**Comment by qq88797833** [comment]
![image](https://github.com/pixpark/gpupixel/assets/28855943/9306c0ba-9599-44ce-87ef-c19d35940053)
兄弟你这个怎么编译过得

**Comment by KakaWan** [comment]
> ![image](https://private-user-images.githubusercontent.com/28855943/330361932-9306c0ba-9599-44ce-87ef-c19d35940053.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MzcyODIsIm5iZiI6MTcxNTczNjk4MiwicGF0aCI6Ii8yODg1NTk0My8zMzAzNjE5MzItOTMwNmMwYmEtOTU5OS00NGNlLTg3ZWYtYzE5ZDM1OTQwMDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDAxMzYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MjA5ZjE3ZjQ0OGExNGYxOGQzMTVjMmZhMWYwNjg4YTA2MTU4MWQ3MGQ2ZDMxODU5NWFhMjRhNzVjZjRhYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xWstTYE7ox1Q6eOlWhLpXMxKYTR36iPHedjJdQBnvvA) 兄弟你这个怎么编译过得

按这个配置去编译就行：
https://github.com/pixpark/gpupixel/issues/50#issuecomment-2058162394
