### ISSUE TITLE
[BUG] windows 编译，这个动态库错误

### ISSUE THREAD

**Issue by ckJust** [pixpark/gpupixel#63]
![image](https://github.com/pixpark/gpupixel/assets/28855943/31a9bd59-fa66-41d4-92c3-d7705eb7f31b)

**Comment by VictorQiuYY** [comment]
> app编译不过， ![image](https://private-user-images.githubusercontent.com/28855943/330361738-ad8f4d2d-73aa-4d8f-981d-2982d02e44ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MjA5NzgsIm5iZiI6MTcxNzkyMDY3OCwicGF0aCI6Ii8yODg1NTk0My8zMzAzNjE3MzgtYWQ4ZjRkMmQtNzNhYS00ZDhmLTk4MWQtMjk4MmQwMmU0NGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDA4MTExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNjM5Y2FkNGY5N2ZhM2JhYzVjYmRiZjNiNTlhZGJiODVkOGU3ODIzYzVkNTc1MzMxNDc1YjUwYjEzYTNiNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.of6ynhsHinEiEkdD1ExDfWbv3c3bY4vTyzN2EGTBNSE)

请问解决了吗 ？ 有处理方式吗 ？ 我也是在做动态链接库封装时候出现的这个问题

**Comment by ckJust** [comment]
直接将dll改exe，或者重新导入dll 。作者的dll 导出头文件msvc应该有些问题，然后模型的路径要记得写对就可以运行，效果好不错

**Comment by ckJust** [comment]
1

**Comment by VictorQiuYY** [comment]
> 直接将dll改exe，或者重新导入dll 。作者的dll 导出头文件msvc应该有些问题，然后模型的路径要记得写对就可以运行，效果好不错

已经研究成功了？可以教教我么
