### ISSUE TITLE
[Bug] Got empty output when first calling SourceRawDataInput-> uploadBytes.

### ISSUE THREAD

**Issue by quqixun** [pixpark/gpupixel#66]
I have read "How to Use" section in README, desktop app and https://github.com/pixpark/gpupixel/issues/54 :
- https://github.com/pixpark/gpupixel?tab=readme-ov-file#how-to-use
- https://github.com/pixpark/gpupixel/blob/main/examples/desktop/app.cc
- https://github.com/pixpark/gpupixel/issues/54#issuecomment-2097351930

I tried to demo a simple example using SourceRawDataInput and TargetRawDataOutput in C++.
However, empty output data was obtained in target_raw_output->setPixelsCallbck when first calling source_raw_input->uploadBytes.
What is going on here? How to fix it?
Thanks.

```c++
#include <glad/glad.h>
#include <GLFW/glfw3.h>

#include <iostream>
#include "gpupixel.h"
using namespace gpupixel;

#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"


std::shared_ptr<SourceRawDataInput> source_raw_input;
std::shared_ptr<TargetRawDataOutput> target_raw_output;
std::shared_ptr<BeautyFaceFilter> beauty_face_filter;
std::shared_ptr<FaceReshapeFilter> face_reshape_filter;
std::shared_ptr<LipstickFilter> lipstick_filter;
std::shared_ptr<BlusherFilter> blusher_filter;


// check values of first row of image
void checkImageDataValue(const uint8_t* imageData, int width, int height, int channels) {
    for (int y = 0; y < height; ++y) {
        for (int x = 0; x < width; ++x) {
            for (int c = 0; c < channels; ++c) {
                std::cout << y << " " << x << " " << c << " " << imageData[(y * width + x) * channels + c] << std::endl;
                break;
            }
            break;
        }
    }
}


int main(int argc, char* argv[])
{

    std::string imagePath = "demo.png";
    float beautyValue = 0.0;
    float whithValue = 0.0;
    float thinFaceValue = 0.0;
    float bigeyeValue = 0.0;
    float lipstickValue = 0.0;
    float blusherValue = 0.0;

    // read input image
    int width, height, channel;
    uint8_t* imageData = stbi_load(imagePath.c_str(), &width, &height, &channel, 0);
    if(imageData == nullptr) {
        std::cerr << "Failed to read image" << std::endl;
        return -1;
    }

    GLFWwindow* window = GPUPixelContext::getInstance()->GetGLContext();
    if (window == NULL) {
        std::cout << "Failed to create GLFW window" << std::endl;
        glfwTerminate();
        return -1;
    }
    glfwMakeContextCurrent(window);
    // glad: load all OpenGL function pointers
    if (!gladLoadGLLoader((GLADloadproc)glfwGetProcAddress)) {
        std::cout << "Failed to initialize GLAD" << std::endl;
        return -1;
    }

    GPUPixelContext::getInstance()->runSync([&] {
        source_raw_input = SourceRawDataInput::create();
        face_reshape_filter = FaceReshapeFilter::create();
        lipstick_filter = LipstickFilter::create();
        blusher_filter = BlusherFilter::create();
        beauty_face_filter = BeautyFaceFilter::create();
        target_raw_output = TargetRawDataOutput::create();        

        source_raw_input->RegLandmarkCallback([=](std::vector<float> landmarks) {

            // check landmarks, correct
            // std::cout << "landmarks:" << std::endl;
            // for (size_t i = 0; i < landmarks.size(); ++i) {
            //     std::cout << landmarks[i] << " ";
            // }
            // std::cout << std::endl;

            lipstick_filter->SetFaceLandmarks(landmarks);
            blusher_filter->SetFaceLandmarks(landmarks);
            face_reshape_filter->SetFaceLandmarks(landmarks);
        });

        target_raw_output->setPixelsCallbck([=](const uint8_t* outputData,
                                                int outputWidth,
                                                int outputHeight,
                                                int64_t ts) {
            std::cout << "channel: " << channel << std::endl;
            std::cout << "outputWidth: " << outputWidth << std::endl;
            std::cout << "outputHeight: " << outputHeight << std::endl;

            // ------------------------------------------------------------------------------
            // empty outputData when first calling source_raw_input->uploadBytes
            checkImageDataValue(outputData, outputWidth, outputHeight, channel);
            // ------------------------------------------------------------------------------
        });

        source_raw_input->addTarget(lipstick_filter)
                    ->addTarget(blusher_filter)
                    ->addTarget(face_reshape_filter)
                    ->addTarget(beauty_face_filter)
                    ->addTarget(target_raw_output);
    });

    beauty_face_filter->setBlurAlpha(beautyValue / 10);
    beauty_face_filter->setWhite(whithValue / 20);
    face_reshape_filter->setFaceSlimLevel(thinFaceValue / 200);
    face_reshape_filter->setEyeZoomLevel(bigeyeValue / 100);
    lipstick_filter->setBlendLevel(lipstickValue / 10);
    blusher_filter->setBlendLevel(blusherValue / 10);

    source_raw_input->uploadBytes(imageData, width, height, width);  // got empty outputData
    source_raw_input->uploadBytes(imageData, width, height, width);  // got correct outputData

    stbi_image_free(imageData);
    return 0;
}

```

**Comment by 205418367** [comment]
问题解决了么/

**Comment by qwonderkid** [comment]
I've met similar issues. Try continously uploadbytes.
while(true)
{
      source_raw_input->uploadBytes(imageData, width, height, width);
}
Then get the correct output

**Comment by 205418367** [comment]
你用什么方法把图片保存到本地？我用下面这个方法得到的结果不符合预期。
stbi_write_jpg(name.c_str(), outputWidth, outputHeight, channel, outputData, 100);

**Comment by qwonderkid** [comment]
> 你用什么方法把图片保存到本地？我用下面这个方法得到的结果不符合预期。 stbi_write_jpg(name.c_str(), outputWidth, outputHeight, channel, outputData, 100);

cv::Mat output(height,width,CV_8UC4,outputData);
cv::imwrite("output.jpg',output);
结果的rgb可能有误，需要cvtcolor一下

**Comment by quqixun** [comment]
> I've met similar issues. Try continously uploadbytes. while(true) { source_raw_input->uploadBytes(imageData, width, height, width); } Then get the correct output

Thanks. It works.
The while loop is not necessary. I tried to run two time uploadBytes :
```c++
source_raw_input->uploadBytes(imageData, width, height, width);  // got empty outputData
source_raw_input->uploadBytes(imageData, width, height, width);  // got correct outputData
```

I think it is a bug.

**Comment by 205418367** [comment]
对，有点不合理，可以反馈一下

**Comment by 205418367** [comment]
> > I've met similar issues. Try continously uploadbytes. while(true) { source_raw_input->uploadBytes(imageData, width, height, width); } Then get the correct output
> 
> Thanks. It works. The while loop is not necessary. I tried to run two time uploadBytes :
> 
> ```c++
> source_raw_input->uploadBytes(imageData, width, height, width);  // got empty outputData
> source_raw_input->uploadBytes(imageData, width, height, width);  // got correct outputData
> ```
> 
> I think it is a bug.

对，有点不合理，可以反馈一下

**Comment by 205418367** [comment]
> > 你用什么方法把图片保存到本地？我用下面这个方法得到的结果不符合预期。 stbi_write_jpg(name.c_str(), outputWidth, outputHeight, channel, outputData, 100);
> 
> cv::Mat output(height,width,CV_8UC4,outputData); cv::imwrite("output.jpg',output); 结果的rgb可能有误，需要cvtcolor一下

我换成opencv还是一样的问题呢
![Uploading output.jpg…]()

**Comment by 205418367** [comment]
> > 你用什么方法把图片保存到本地？我用下面这个方法得到的结果不符合预期。 stbi_write_jpg(name.c_str(), outputWidth, outputHeight, channel, outputData, 100);
> 
> cv::Mat output(height,width,CV_8UC4,outputData); cv::imwrite("output.jpg',output); 结果的rgb可能有误，需要cvtcolor一下

我换成opencv还是一样的问题呢
![Uploading output.jpg…]()

**Comment by 205418367** [comment]
> > 你用什么方法把图片保存到本地？我用下面这个方法得到的结果不符合预期。 stbi_write_jpg(name.c_str(), outputWidth, outputHeight, channel, outputData, 100);
> 
> cv::Mat output(height,width,CV_8UC4,outputData); cv::imwrite("output.jpg',output); 结果的rgb可能有误，需要cvtcolor一下

我换成opencv还是一样的问题呢
[Uploading output.zip…]()

**Comment by 205418367** [comment]
> > 你用什么方法把图片保存到本地？我用下面这个方法得到的结果不符合预期。 stbi_write_jpg(name.c_str(), outputWidth, outputHeight, channel, outputData, 100);
> 
> cv::Mat output(height,width,CV_8UC4,outputData); cv::imwrite("output.jpg',output); 结果的rgb可能有误，需要cvtcolor一下
用opencv 还是有点问题
[output.zip](https://github.com/pixpark/gpupixel/files/15467780/output.zip)

**Comment by qwonderkid** [comment]
> > > 你用什么方法把图片保存到本地？我用下面这个方法得到的结果不符合预期。 stbi_write_jpg(name.c_str(), outputWidth, outputHeight, channel, outputData, 100);
> > 
> > 
> > cv::Mat output(height,width,CV_8UC4,outputData); cv::imwrite("output.jpg',output); 结果的rgb可能有误，需要cvtcolor一下
> > 用opencv 还是有点问题
> > [output.zip](https://github.com/pixpark/gpupixel/files/15467780/output.zip)

看起来是通道数错了

**Comment by 205418367** [comment]
> > > > 你用什么方法把图片保存到本地？我用下面这个方法得到的结果不符合预期。 stbi_write_jpg(name.c_str(), outputWidth, outputHeight, channel, outputData, 100);
> > > 
> > > 
> > > cv::Mat output(height,width,CV_8UC4,outputData); cv::imwrite("output.jpg',output); 结果的rgb可能有误，需要cvtcolor一下
> > > 用opencv 还是有点问题
> > > [output.zip](https://github.com/pixpark/gpupixel/files/15467780/output.zip)
> 
> 看起来是通道数错了

你是怎么解决的呢？

**Comment by 205418367** [comment]
> > > > 你用什么方法把图片保存到本地？我用下面这个方法得到的结果不符合预期。 stbi_write_jpg(name.c_str(), outputWidth, outputHeight, channel, outputData, 100);
> > > 
> > > 
> > > cv::Mat output(height,width,CV_8UC4,outputData); cv::imwrite("output.jpg',output); 结果的rgb可能有误，需要cvtcolor一下
> > > 用opencv 还是有点问题
> > > [output.zip](https://github.com/pixpark/gpupixel/files/15467780/output.zip)
> 
> 看起来是通道数错了

解决了！！！

**Comment by quqixun** [comment]
@205418367 你好，可以把与issue不相关的内容删除一下吗？

**Comment by tu461987807** [comment]
i've get similar issues.

**Comment by tu461987807** [comment]
in TargetRawDataOutput::readPixelsWithPBO function ，when I annotated these two sentences, it was fine
  //index = (index + 1) % 2;
  //nextIndex = (index + 1) % 2;

**Comment by quqixun** [comment]
> in TargetRawDataOutput::readPixelsWithPBO function ，when I annotated these two sentences, it was fine //index = (index + 1) % 2; //nextIndex = (index + 1) % 2;

Thanks. It works.

**Comment by VictorQiuYY** [comment]
![image](https://github.com/pixpark/gpupixel/assets/47585072/7357af28-8156-4ef0-97bc-0e8d687d2c56)
 怎么编译动态链接库啊。 需要改什么？。 现在编译后一直提示 无法解析的外部符号。 我试了很多编译方式都没有成功

**Comment by songtianhui** [comment]
Hello, I follow your steps and have some questions. The callback function of `target_raw_output` seems not been executed. I add some log print in the callback, but no output. Here is my code, can you help to check any bugs?
```c++
#include <glad/glad.h>
#include <GLFW/glfw3.h>

#include <iostream>
#include "gpupixel.h"
#include "stb_image.h"
using namespace gpupixel;

// video data input
std::shared_ptr<SourceRawDataInput> source_raw_input_;
// beauty filter
std::shared_ptr<BeautyFaceFilter> beauty_face_filter_;
// video data output 
std::shared_ptr<TargetRawDataOutput> target_raw_output_;

uint8_t* output_buffer;


void error_callback( int error, const char *msg ) {
    std::string s;
    s = " [" + std::to_string(error) + "] " + msg + '\n';
    std::cerr << s << std::endl;
}


int main() {
    glfwSetErrorCallback(error_callback);
    GLFWwindow* window = GPUPixelContext::getInstance()->GetGLContext();
  
    if (window == NULL)
    {
        std::cout << "Failed to create GLFW window" << std::endl;
        glfwTerminate();
        return -1;
    }

    // glfwShowWindow(window);

    glfwMakeContextCurrent(window);
    // glfwSetFramebufferSizeCallback(window, framebuffer_size_callback);
 
    // glad: load all OpenGL function pointers
    // ---------------------------------------
    if (!gladLoadGLLoader((GLADloadproc)glfwGetProcAddress))
    {
        std::cout << "Failed to initialize GLAD" << std::endl;
        return -1;
    }

    // bytes: RGBA data
    int width, height, channel;
    unsigned char *bytes = stbi_load("demo.png", &width, &height, &channel, 0);
    std::cout << "width: " << width << std::endl;
    std::cout << "height: " << height << std::endl;
    std::cout << "channel: " << channel << std::endl;

    gpupixel::GPUPixelContext::getInstance()->runSync([&] {
        // Create filter
        source_raw_input_ = SourceRawDataInput::create();
        target_raw_output_ = TargetRawDataOutput::create();
        // Face Beauty Filter
        beauty_face_filter_ = BeautyFaceFilter::create();

        // target output set callbck
        target_raw_output_->setPixelsCallbck([=](const uint8_t *data, int width, int height, int64_t ts) {
            size_t rgba_size = width * height * 4;
            // Do something you want
            for (size_t i = 0; i < rgba_size; ++i) {
                output_buffer[i] = data[i];
                std::cout << output_buffer[i] << std::endl;
            }
        });

        // Add filter
        source_raw_input_->addTarget(beauty_face_filter_)->addTarget(target_raw_output_);
    });

    beauty_face_filter_->setWhite(100);

    // input
    output_buffer = new uint8_t[width * height * channel];
    source_raw_input_->uploadBytes(bytes, width, height, channel);

    stbi_image_free(bytes);
    return 0;
}
```
