### ISSUE TITLE
我在linux上运行，想把结果保存到本地，怎么实现？

### ISSUE THREAD

**Issue by 205418367** [pixpark/gpupixel#67]

**Comment by gezhaoyou** [comment]
通过 https://github.com/pixpark/gpupixel/blob/main/src/target/target_raw_data_output.cc，参考 readme 中有介绍

**Comment by 205418367** [comment]
大佬，我测了不行呢！帮忙看看或者给个demo?
[main.zip](https://github.com/pixpark/gpupixel/files/15463127/main.zip)

**Comment by samwellshi** [comment]
我在ubuntu 24环境下编译例子的时候有个链接错误：
`[100%] Linking CXX executable /root/gpupixel-main/output/app/linux/gpupixel_app
Copying resource files to output/app directory.
/usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__pow_finite'
/usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__powf_finite'
/usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `_ZGVbN2v___log_finite'
/usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `_ZGVbN2vv___pow_finite'
/usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `_ZGVbN4v___logf_finite'
/usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__expf_finite'
/usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__atan2f_finite'
/usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__sinhf_finite'
/usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__coshf_finite'
/usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__atanhf_finite'
/usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__acosf_finite'
/usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__acoshf_finite'
/usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `_ZGVbN4v___expf_finite'
/usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__log_finite'
/usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `_ZGVbN4vv___powf_finite'
/usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__asinf_finite'
/usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__logf_finite'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/gpupixel_app.dir/build.make:100: /root/gpupixel-main/output/app/linux/gpupixel_app] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/gpupixel_app.dir/all] Error 2`

要怎么解决？

**Comment by jaaronkot** [comment]
> 我在ubuntu 24环境下编译例子的时候有个链接错误： `[100%] Linking CXX executable /root/gpupixel-main/output/app/linux/gpupixel_app Copying resource files to output/app directory. /usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__pow_finite' /usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__powf_finite' /usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `_ZGVbN2v___log_finite' /usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `_ZGVbN2vv___pow_finite' /usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `_ZGVbN4v___logf_finite' /usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__expf_finite' /usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__atan2f_finite' /usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__sinhf_finite' /usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__coshf_finite' /usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__atanhf_finite' /usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__acosf_finite' /usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__acoshf_finite' /usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `_ZGVbN4v___expf_finite' /usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__log_finite' /usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `_ZGVbN4vv___powf_finite' /usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__asinf_finite' /usr/bin/ld: /root/gpupixel-main/examples/../output/library/linux/libgpupixel.so: undefined reference to `__logf_finite' collect2: error: ld returned 1 exit status gmake[2]: *** [CMakeFiles/gpupixel_app.dir/build.make:100: /root/gpupixel-main/output/app/linux/gpupixel_app] Error 1 gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/gpupixel_app.dir/all] Error 2`
> 
> 要怎么解决？

尝试main分支最新代码，已修改，或者尝试使用debian10版本编译
