### ISSUE TITLE
请问iOS推metal挺久了，使用OpenGL ES兼容会不会不太好？以后会不会就用不了了？

### ISSUE THREAD

**Issue by xfbedev** [pixpark/gpupixel#7]
如题，担心以后恐怕得iOS安卓维护两套

**Comment by gezhaoyou** [comment]
There is currently no news that Apple will remove OpenGL from iOS or macOS. It's a bit similar to Swift being around for several years while Objective-C still exists. If OpenGL is removed by Apple, there will likely be alternative solutions available. Currently, GPUImage3, developed based on Metal, can be considered.

**Comment by gezhaoyou** [comment]
In the future, there will be consideration for using Vulkan as a unified solution
