### ISSUE TITLE
[BUG]centos上无法安装对应的依赖库

### ISSUE THREAD

**Issue by forrest-lam** [pixpark/gpupixel#70]
使用dnf或yum install无法安装依赖库：
Last metadata expiration check: 1 day, 13:10:14 ago on Tue 28 May 2024 10:15:35 PM CST.
No match for argument: mesa-utils
No match for argument: libglu1-mesa-dev
No match for argument: freeglut3-dev
No match for argument: mesa-common-dev
No match for argument: libglfw3-dev
Error: Unable to find a match: mesa-utils libglu1-mesa-dev freeglut3-dev mesa-common-dev libglfw3-dev

运行cmake时会报错：
/usr/bin/ld: cannot find -lGL
/usr/bin/ld: cannot find -lglfw
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/gpupixel.dir/build.make:1961: /cbs_data/gpupixel/output/library/linux/libgpupixel.so] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/gpupixel.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2

**Comment by jarronkot** [comment]
centos 没有尝试过，问下 gpt 吧，还是依赖的问题
