### ISSUE TITLE
使用windows自带的测试，换了一个demo.png就闪退了。是图片有什么特别的要求吗

### ISSUE THREAD

**Issue by VictorQiuYY** [pixpark/gpupixel#71]
![demo3](https://github.com/pixpark/gpupixel/assets/47585072/8cceb31d-c876-4135-9f12-16ab2c807116)

![image](https://github.com/pixpark/gpupixel/assets/47585072/4b3a8dfd-579c-4380-a935-e4070fa9042c)

**Comment by ckJust** [comment]
请问windows 你是怎么编译过得 msvc 还是mingw, 我卡在test 的demo编译不过

**Comment by qwonderkid** [comment]
facedetect的代码里，丢给vnn做人脸检测的参数默认是4通道的。如果图片是3通道的就会崩溃。可能是这个原因

**Comment by VictorQiuYY** [comment]
> facedetect的代码里，丢给vnn做人脸检测的参数默认是4通道的。如果图片是3通道的就会崩溃。可能是这个原因

测试了，就是这个问题。

**Comment by woshitxm** [comment]
所以，输入图像是RGBA四通道的吗

**Comment by weiyu666** [comment]
也就是说图片如果是jpg的不支持啦？要png 支持rgba四通道？
