### ISSUE TITLE
msvc编译器如何编译

### ISSUE THREAD

**Issue by Calvin-Shen** [pixpark/gpupixel#76]
用了以下命令，生成不了对应的动态库:
PS C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build> .\vcvars64.bat

PS C:\Users\chen.shen\Desktop\gpupixel-main> cmake -G "Visual Studio 16 2019" -A x64 -B build -S src

PS C:\Users\chen.shen\Desktop\gpupixel-main> cmake --build build --config Release

看readme中只有mingw的方式，有没有小伙伴用msvc编译器，编译成功的？

**Comment by hs205118** [comment]
哥们你有搞定没？
我试了，编译有几个小问题。解决了之后，会提示 vnn_core.dll 文件无效或损坏
估计也要更新这个文件，你那有编译好的没？求共享啊

**Comment by Calvin-Shen** [comment]
没编译没过....不知道有没有人通过msvc编译器编译过的。或者有没有其他支持msvc编译器的  美颜 的库推荐？感谢

**Comment by jarronkot** [comment]
> 我改了一下，编译过了。[https://github.com/GGGGYZ/gpupixel/tree/msvc](url)

希望提个 PR

**Comment by Calvin-Shen** [comment]
> 我改了一下，编译过了。[https://github.com/GGGGYZ/gpupixel/tree/msvc](url)
可以正常使用么？

**Comment by hs205118** [comment]
我用上面的代码编译通过了，但是运行的时候，会直接崩溃，菜鸟一枚，不知道原因。没运行起来作者的效果

**Comment by Calvin-Shen** [comment]
> 我改了一下，编译过了。[https://github.com/GGGGYZ/gpupixel/tree/msvc](url)

点个赞，demo已经跑起来了

**Comment by hs205118** [comment]
大神能优化针对“景点拍照，全身照，有人，有远景的”这样的应用场景做修改不？
