### ISSUE TITLE
Does anyone build it on Ubuntu successfully?

### ISSUE THREAD

**Issue by AlvinChen1028** [pixpark/gpupixel#8]
As titled.

**Comment by gezhaoyou** [comment]
The support for Linux systems is already being planned

**Comment by gezhaoyou** [comment]
Now gpupixel support linux from v1.10.

**Comment by AlvinChen1028** [comment]
> Now gpupixel support linux from v1.10.

The lib can be generated on Ubuntu well on main branch. But the example for desktop can't be generated, and in 'desktop' folder, there is only one file 'app.cc', but no cmake configure file.

**Comment by gezhaoyou** [comment]
> > Now gpupixel support linux from v1.10.
> 
> The lib can be generated on Ubuntu well on main branch. But the example for desktop can't be generated, and in 'desktop' folder, there is only one file 'app.cc', but no cmake configure file.

cd to  `example` dir , 
```
mkdir build 
cd build 
cmake ..
make
```

**Comment by AlvinChen1028** [comment]
> > > Now gpupixel support linux from v1.10.
> > 
> > 
> > The lib can be generated on Ubuntu well on main branch. But the example for desktop can't be generated, and in 'desktop' folder, there is only one file 'app.cc', but no cmake configure file.
> 
> cd to `example` dir ,
> 
> ```
> mkdir build 
> cd build 
> cmake ..
> make
> ```

It works. Thank you! 
BTW, I try to run gpupixel_app on Ubuntu 20.04, it runs with core dump.
![Uploading MicrosoftTeams-image (3).png…]()

**Comment by AlvinChen1028** [comment]
> > > Now gpupixel support linux from v1.10.
> > 
> > 
> > The lib can be generated on Ubuntu well on main branch. But the example for desktop can't be generated, and in 'desktop' folder, there is only one file 'app.cc', but no cmake configure file.
> 
> cd to `example` dir ,
> 
> ```
> mkdir build 
> cd build 
> cmake ..
> make
> ```

Thanks. It works.
BTW, the Linux demo app doesn't include face slim and big eye. Right?

**Comment by gezhaoyou** [comment]
Yes, because there is no suitable face recognition library for Linux and Windows, so there is no support for thin face. We will try to use vnn to implement it in the future.

**Comment by AlvinChen1028** [comment]
> Yes, because there is no suitable face recognition library for Linux and Windows, so there is no support for thin face. We will try to use vnn to implement it in the future.

I am trying to make a sample for raw image (raw rgba), but failed: the sample code is like:

// video data input
std::shared_ptr<SourceRawDataInput> source_raw_input_;
// beauty filter
std::shared_ptr<BeautyFaceFilter> beauty_face_filter_;
// video data output 
std::shared_ptr<TargetRawDataOutput> target_raw_output_;

 gpupixel::GPUPixelContext::getInstance()->runSync([&] {
    // Create filter
    source_raw_input_ = SourceRawDataInput::create();
    target_raw_output_ = TargetRawDataOutput::create();
    // Face Beauty Filter
    beauty_face_filter_ = BeautyFaceFilter::create();
    
    // Add filter
    source_raw_input_->addTarget(beauty_face_filter_)
                     ->addTarget(target_raw_output_);
 }
// ...
// bytes: RGBA data
fread(bytes, ...); // Read raw RGBA data from file.
 source_raw_input_->uploadBytes(bytes,
                                width, 
                                height, 
                                stride);

// RGBA callback->
target_raw_output_->setPixelsCallbck([=](const uint8_t *data, 
                                        int width, 
                                        int height, 
                                        int64_t ts) {
    size_t rgba_size = width * height*4;
    // Do something you want
});

What need I to do for next step to trigger the process? I try to call 'source_raw_input_->proceed()", but it is failed.

Do you have any samples for raw image?

**Comment by gezhaoyou** [comment]
try v1.1.1

**Comment by AlvinChen1028** [comment]
Thank you! Could you please commit the sample if you have？

**Comment by AlvinChen1028** [comment]
> try v1.1.1

Thank you! Could you please commit the sample if you have？
