### ISSUE TITLE
[BUG]编译报错

### ISSUE THREAD

**Issue by xmubingo** [pixpark/gpupixel#83]
[ 96%] Building CXX object CMakeFiles/gpupixel.dir/utils/dispatch_queue.cc.o
[ 97%] Building CXX object CMakeFiles/gpupixel.dir/utils/math_toolbox.cc.o
[ 98%] Building CXX object CMakeFiles/gpupixel.dir/utils/util.cc.o
[ 99%] Building C object CMakeFiles/gpupixel.dir/third_party/glad/src/glad.c.o
[100%] Linking CXX shared library /xxx/gpupixel/output/library/linux/libgpupixel.so
Copying headers and resource to output directory.
/usr/bin/ld: 找不到 -lGL
/usr/bin/ld: 找不到 -lglfw
collect2: 错误：ld 返回 1
gmake[2]: *** [/xxx/gpupixel/output/library/linux/libgpupixel.so] 错误 1
gmake[1]: *** [CMakeFiles/gpupixel.dir/all] 错误 2
gmake: *** [all] 错误 2

**Comment by jarronkot** [comment]
链接错误，缺少gl 相关依赖，参考：https://gpupixel.pixpark.net/zh/guide/build#linux-test-on-ubuntu
