### ISSUE TITLE
Question about FaceMakeupFilter landmarks

### ISSUE THREAD

**Issue by leon4app** [pixpark/gpupixel#9]
repo 的实时视频和图像的能力令人印象深刻，在研究您的项目时，我对其中的 FaceMakeupFilter 功能产生了一些疑问，希望能得到您的解答。

在 DEMO 中有实现两个 Filter，分别是`blusher_filter_`和`lipstick_filter_`，它们是如何与landmarks协同去定位面部位置的呢？这里有几点没有理解：
- 从代码看它们使用的是同一个类`FaceMakeupFilter`，唯一的差别是`setTextureBounds`的位置不同，是不是意味着 filters 并不知道什么叫嘴什么叫腮，它仅仅是根据TextureBounds去做形变？
- 这两个滤镜的TextureBounds `FrameBounds{502.5, 710, 262.5, 167.5}`和`FrameBounds{395, 520, 489, 209}`是如何得到的呢？如果我想要去实现一个新的滤镜，该如何确定这些值？
- 我试了一下口红滤镜，它能够准确避免牙齿被上色，这是似乎是通过faceIndexs对嘴部的三角形进行着色实现的？但是mouth 是一张图片，并不是一个颜色，它是如何形变去适配嘴部区域的？尤其是考虑到前面的第一点：FaceMakeupFilter应该并不知道它的实例的想要美化的是嘴还是腮？

I'm thoroughly impressed with your real-time video and image processing library on GitHub. While exploring your project, I have some questions about the FaceMakeupFilter feature and would appreciate your insights.

In the DEMO, two filters are implemented: blusher_filter_ and lipstick_filter_. I'm intrigued by how they work in conjunction with facial landmarks. Here are my questions:
- Both filters seem to use the same FaceMakeupFilter class, with the main difference being the placement of setTextureBounds. Does this mean that the filters don't directly recognize specific facial areas like the mouth or cheeks, and instead deform based on TextureBounds?
- How are the TextureBounds for blusher_filter_ and lipstick_filter_ determined? For instance, how were values like FrameBounds{502.5, 710, 262.5, 167.5} and FrameBounds{395, 520, 489, 209} arrived at? If I want to implement a new filter, how should I determine the values for these TextureBounds?
- I tried the lipstick filter and noticed its precise avoidance of coloring the teeth, apparently achieved by coloring the mouth's triangles using faceIndexs. However, if the mouth is represented as an image rather than a single color, how does it deform to fit the mouth area? This is particularly intriguing considering FaceMakeupFilter might not differentiate whether it's being used for the mouth or cheeks.

**Comment by gezhaoyou** [comment]
In the future, I will write a dedicated series of articles explaining the principles of the SDK. However, my resources are limited, so please be patient and wait for it. Thank you.

**Comment by dsxlong** [comment]
@leon4app 你好，有研究出TextureBounds的原理吗？
   auto mouth = SourceImage::create("mouth.png");
    lipstick_filter_ = FaceMakeupFilter::create();
    lipstick_filter_->setImageTexture(mouth);
    lipstick_filter_->setTextureBounds(FrameBounds{502.5, 710, 262.5, 167.5});

    auto blusher = SourceImage::create("blusher.png");
    blusher_filter_ = FaceMakeupFilter::create();
    blusher_filter_->setImageTexture(blusher);
    blusher_filter_->setTextureBounds(FrameBounds{395, 520, 489, 209});

**Comment by gezhaoyou** [comment]
TextureBounds FrameBounds{502.5, 710, 262.5, 167.5}和FrameBounds{395, 520, 489, 209}  这两组值是固定的，是嘴巴和腮部在人脸上的位置和区域。是因为计算的坐标是按照一张固定的标准人脸或者说平均人脸来确定的，标准人脸图可以由设计师来创建，确定人脸上各个点的坐标。然后转换为纹理采样的坐标，范围在[0, 1] 之间。

**Comment by WoYang** [comment]
> TextureBounds FrameBounds{502.5, 710, 262.5, 167.5}和FrameBounds{395, 520, 489, 209} 这两组值是固定的，是嘴巴和腮部在人脸上的位置和区域。是因为计算的坐标是按照一张固定的标准人脸或者说平均人脸来确定的，标准人脸图可以由设计师来创建，确定人脸上各个点的坐标。然后转换为纹理采样的坐标，范围在[0, 1] 之间。

 Hi，这里把纹理坐标重新进行了计算对齐到顶点坐标，这个转换原理没有看懂
        for (int i = 0; i < point_count; i++) {
            textureCoordinates[i * 2 + 0] =(coord[i * 2 + 0] * 1280 - texture_bounds_.x) / texture_bounds_.width;
            textureCoordinates[i * 2 + 1] =(coord[i * 2 + 1] * 1280 - texture_bounds_.y) / texture_bounds_.height;
        }

**Comment by Jasper2016** [comment]
> TextureBounds FrameBounds{502.5, 710, 262.5, 167.5}和FrameBounds{395, 520, 489, 209} 这两组值是固定的，是嘴巴和腮部在人脸上的位置和区域。是因为计算的坐标是按照一张固定的标准人脸或者说平均人脸来确定的，标准人脸图可以由设计师来创建，确定人脸上各个点的坐标。然后转换为纹理采样的坐标，范围在[0, 1] 之间。

标准人脸图片可以分享一下吗？

**Comment by dsxlong** [comment]
这个问题已经搞清楚了，谢谢你。
