### ISSUE TITLE
[Feature Request]作者大大，手机只有后置摄像头，我应该在哪里修改代码

### ISSUE THREAD

**Issue by 1615070057** [pixpark/gpupixel#93]
作者大大，手机只有后置摄像头，我应该在哪里修改代码

**Comment by jaaronkot** [comment]
调用这个接口切换摄像头：https://github.com/pixpark/gpupixel/blob/05fd136911723e702645388186e159be04e62ba4/src/android/java/gpupixel/src/main/java/com/pixpark/gpupixel/GPUPixelSourceCamera.java#L95C17-L95C29

**Comment by jaaronkot** [comment]
https://github.com/pixpark/gpupixel/blob/05fd136911723e702645388186e159be04e62ba4/src/android/java/gpupixel/src/main/java/com/pixpark/gpupixel/GPUPixelSourceCamera.java#L95
