### ISSUE TITLE
大佬，在你的安卓demo中，将前置摄像头改为后置之后，图像是倒立的

### ISSUE THREAD

**Issue by 1615070057** [pixpark/gpupixel#98]
大佬，在你的安卓demo中，将前置摄像头改为后置之后，图像是倒立的，我改了setUpCamera里面的旋转操作，感觉没有变化。
source_camera里面好像有旋转图像的操作，但怎么感觉是ios开发的

**Comment by 1615070057** [comment]
setUpCamera返回的图像旋转模式是正确的，为什么最后显示的图像是倒立

**Comment by 5dprince** [comment]
解决了吗?我 也遇到这个倒立的了...

**Comment by 1615070057** [comment]
在OpenGL中，纹理坐标的原点（0,0）位于左下角，而屏幕坐标原点（0,0）位于左上角，需要传个纹理坐标进去

![微信图片_20240919011237](https://github.com/user-attachments/assets/50ea7f66-264c-4233-b0fd-3891debd9133)

**Comment by Hongbin4950** [comment]
> 在OpenGL中，纹理坐标的原点（0,0）位于左下角，而屏幕坐标原点（0,0）位于左上角，需要传个纹理坐标进去
> 
> ![微信图片_20240919011237](https://private-user-images.githubusercontent.com/47350390/368670750-50ea7f66-264c-4233-b0fd-3891debd9133.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMTY3OTIsIm5iZiI6MTczMzExNjQ5MiwicGF0aCI6Ii80NzM1MDM5MC8zNjg2NzA3NTAtNTBlYTdmNjYtMjY0Yy00MjMzLWIwZmQtMzg5MWRlYmQ5MTMzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA1MTQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjODhjOTFhZjY1Njg1NTcwMTQ0YWYxZGRlZjYyOThmMDUzMmRiMjEzMTBiMzAzYWJhYzVlOWU2MDU0OGE2MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kGtNCPGV9ukYZ_tCVGCttkd1nxmTGE-O31DW2XJrHw8)

大佬，我不是很懂opengl  请问一下这个具体是在哪加上去的呢

**Comment by woshitxm** [comment]
应该是一个变换坐标
